name: my_todo_app
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  simple_moment: ^1.1.1 #parsing and date manipulation

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  generate: true

  assets:
     - assets/images/


